### ISSUE TITLE
Sidebar still shows Ease, not Difficulty

### ISSUE THREAD

**Issue by omega3** [noobj2/Anki-Advanced-Review-Bottombar#78]
When Anki switched to FSRS Card Info option shows Difficulty. This add-on still shows Ease factor (or something that is not correctly counted).
Example:
https://i.imgur.com/zXwCKuP.png
On the left: built-in Card Info, on the right: add-on Sidebar.

Version ⁨23.10.1 (fac9e0ee)⁩
Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
with updated add-on version → 23.10+ (Updated 2023-11-17)

**Comment by noobj2** [comment]
I'll work on these as soon as I get some free time (just finished midterms and finals are in a couple of weeks, so I'm kind of busy with exams rn)

**Comment by noobj2** [comment]
I'm working on the add-on right now.
The only difference I found in the built-in and the ARBb card info was the ease factor for rescheduled card.
I rescheduled a card in one of my decks, it still shows the ease factor correctly.
I don't know if the ease always shows the wrong number for you, but if it does, I'd appreciate it if you could tell me the steps to replicate the issue.

because as I said, I rescheduled a card and it still shows me the correct ease.

But if you're talking about Rating/Button thingy. As the rating represents the button (0 for rescheduled cards), I just replaced them with the respective button titles to make it easier to understand.

**Comment by omega3** [comment]
In the Ease column you can see the difference: on the left D:61% on the right 71%.
I believe on the left  (anki build-in) is correct Difficulty. 
Another example 
https://i.imgur.com/LOpjlPd.png
As you can see there is D:
which indicates Difficulty not Ease. From what I read in FSRS there is no Ease. Actually this name "Easy" perhaps should be removed from Anki and replaced by "Difficulty".

But to be honest I don't have such deep understanding of the new scheduling and statistics behind it. Let's wait and see. I will ask about it on Anki forum and get back.

**Comment by omega3** [comment]
As anki shows now in Card Info "Difficulty" not Ease 
https://i.imgur.com/LOpjlPd.png
should the column be called "Difficulty"? From what I read there is no "Ease" factor anymore in new anki versions? Is that correct?

https://github.com/open-spaced-repetition/fsrs4anki/wiki/ABC-of-FSRS
Difficulty (D): The inherent complexity of a particular information. It represents how difficult it is to increase memory stability after a review.

**Comment by omega3** [comment]
[Response](https://forums.ankiweb.net/t/how-to-use-the-next-generation-spaced-repetition-algorithm-fsrs-on-anki/25415/376):
A card may have both SM2 and FSRS review entries, which is why FSRS entries get the D: prefix.

That confuses me a bit, but I interpret it this way, if someone switched to FSRS older entries will belong to SM2, newer to FSRS. Although I don't know how this refers to Anki code. As a user I'd expect that both Card info and this add-on shows the same for a particular card. The first screenshot that I attached shows otherwise.

**Comment by noobj2** [comment]
Thank you very much.
The information was really helpful.
I'll fix it in a few days.

**Comment by noobj2** [comment]
Fixed

**Comment by omega3** [comment]
Have you pushed this fix to files yet? I removed add-on, downloaded it again from anki add-ons and I still see 10% difference in current card:
https://i.imgur.com/8l6x9xT.png
https://i.imgur.com/F5orgsQ.png

**Comment by noobj2** [comment]
Damn. I noticed it now. there's a mistake in the code. I'll push an update tonight. Thanks for the report.

**Comment by noobj2** [comment]
Can you check if it's fixed now? (there might be a 1 percent difference in some cases)

**Comment by omega3** [comment]
I updated and I still see 10% difference:
https://i.imgur.com/P29F9Yo.png
Maybe you may just copy this part of code from Anki? 
https://github.com/ankitects/anki/commit/75de1f9709a6252bff3d619c130cd538117a9dc9

https://github.com/ankitects/anki/tree/main/ts/card-info

**Comment by noobj2** [comment]
That sidebar is the older version.
can you check if your add-on is the latest version? (go to the add on settings menu, `about` tab and then click on `show changelog` button)
the latest entry (at the top) should be `v3.4.3`

**Comment by noobj2** [comment]
> Maybe you may just copy this part of code from Anki?

https://github.com/ankitects/anki/blob/80c14aa6e91eb913ac46be255d845a29a21db043/ts/card-info/Revlog.svelte#L77
This ia how anki calculates the difficulty (it's done in javscript)

I just wrote the same code in python:
https://github.com/noobj2/Anki-Advanced-Review-Bottombar/blob/374efbe49b89d7bc2c0e37b3a557e6ba0f374aea/Card_Info.py#L169

let's say the ease factor is `2500`. anki first divides it by `10`, then if the value is above `110`, it means it's the older ease
if it's equal or below `110` it's the new difficulty in which case it subtracts `10` from it and then rounds it to the nearest integer that's how the difficulty is calculated.

in the rounding stage, if the value's decimal point is `0.5` javascript rounds it up which makes it `1`, but for some reason python rounds it down which makes it `0`, hence the `%1` difference.

**Comment by omega3** [comment]
It is ok now. Thank you very much.

https://i.imgur.com/lgbqLWs.png
https://i.imgur.com/OJ1X7nG.png

Maybe I mistook the versions 2 days ego. It this was the case, accept my apologies. 

Thank you again for this excellent and very useful add-on.

**Comment by noobj2** [comment]
Thank you for your kind words :D
